### ISSUE TITLE
get_R struggles with incidence as a vector

### ISSUE THREAD

**Issue by jeskarp** [reconhub/earlyR#2]
It might be useful to mention somewhere that incidence needs to be an integer? 
Alternatively, there could be an error message if incidence is not in integer form?

[get_R_issue.pdf](https://github.com/reconhub/earlyR/files/1907514/get_R_issue.pdf)

**Comment by thibautjombart** [comment]
@jeskarp can you confirm if this is still live or fixed?

**Comment by jeskarp** [comment]
@thibautjombart  It's fixed.

**Comment by thibautjombart** [comment]
Cool ! :)
